-- Run this script in your Supabase SQL Editor to initialize the database
-- =============================================
-- 1. USERS TABLE (Custom Auth)
-- =============================================
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  "fullName" TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student',
  gender TEXT,
  region TEXT,
  "avatarUrl" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
);
-- =============================================
-- 2. TESTS TABLE (groups questions together)
-- =============================================
CREATE TABLE IF NOT EXISTS public.tests (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
);
-- =============================================
-- 3. QUESTIONS TABLE (belongs to a test)
-- =============================================
CREATE TABLE IF NOT EXISTS public.questions (
  id SERIAL PRIMARY KEY,
  test_id INTEGER NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
  q_text TEXT NOT NULL,
  part TEXT NOT NULL,
  image TEXT,
  speaking_timer INTEGER NOT NULL DEFAULT 30,
  prep_timer INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
);
-- =============================================
-- 4. RESPONSES TABLE (student answer to a question)
-- =============================================
CREATE TABLE IF NOT EXISTS public.responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  local_uri TEXT,
  remote_url TEXT,
  teacher_score INTEGER,
  teacher_feedback TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
);
-- =============================================
-- 5. STORAGE BUCKET FOR AUDIOS
-- =============================================
INSERT INTO
  storage.buckets (id, name, public)
VALUES
  ('audios', 'audios', true) ON CONFLICT (id) DO NOTHING;
-- Storage Policies (drop first to make script re-runnable)
  DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR
SELECT
  USING (bucket_id = 'audios');
DROP POLICY IF EXISTS "Public Uploads" ON storage.objects;
CREATE POLICY "Public Uploads" ON storage.objects FOR
INSERT
  WITH CHECK (bucket_id = 'audios');
DROP POLICY IF EXISTS "Public Update" ON storage.objects;
CREATE POLICY "Public Update" ON storage.objects FOR
UPDATE
  USING (bucket_id = 'audios');
DROP POLICY IF EXISTS "Public Delete" ON storage.objects;
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'audios');
-- =============================================
  -- 6. ROW LEVEL SECURITY (permissive for MVP)
  -- =============================================
ALTER TABLE
  public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE
  public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE
  public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE
  public.responses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for users" ON public.users;
CREATE POLICY "Allow all operations for users" ON public.users FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations for tests" ON public.tests;
CREATE POLICY "Allow all operations for tests" ON public.tests FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations for questions" ON public.questions;
CREATE POLICY "Allow all operations for questions" ON public.questions FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations for responses" ON public.responses;
CREATE POLICY "Allow all operations for responses" ON public.responses FOR ALL USING (true) WITH CHECK (true);
-- =============================================
  -- 7. GROUPS TABLE
  -- =============================================
  CREATE TABLE IF NOT EXISTS public.groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    teacher_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    referral_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
  );
-- =============================================
  -- 8. GROUP MEMBERS TABLE
  -- =============================================
  CREATE TABLE IF NOT EXISTS public.group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL,
    UNIQUE(group_id, student_id)
  );
-- RLS for groups
ALTER TABLE
  public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE
  public.group_members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for groups" ON public.groups;
CREATE POLICY "Allow all operations for groups" ON public.groups FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations for group_members" ON public.group_members;
CREATE POLICY "Allow all operations for group_members" ON public.group_members FOR ALL USING (true) WITH CHECK (true);
-- =============================================
  -- 9. ADD PUSH TOKEN COLUMN TO USERS
  -- =============================================
ALTER TABLE
  public.users
ADD
  COLUMN IF NOT EXISTS push_token TEXT;
-- =============================================
  -- 10. SEED DATA
  -- =============================================
  -- Insert a sample test
INSERT INTO
  public.tests (id, title, description)
VALUES
  (
    1,
    'IELTS Speaking Mock Test 1',
    'A full mock speaking test covering Parts 1, 2, and 3'
  ) ON CONFLICT (id) DO NOTHING;
-- Insert questions belonging to that test
INSERT INTO
  public.questions (
    id,
    test_id,
    q_text,
    part,
    image,
    speaking_timer,
    prep_timer
  )
VALUES
  (
    1,
    1,
    'Tell me about your favorite TV program?',
    '1.1',
    NULL,
    30,
    5
  ),
  (
    2,
    1,
    'Do you like watching TV alone or with other people?',
    '1.1',
    NULL,
    30,
    5
  ),
  (
    3,
    1,
    'Do you often watch TV these days?',
    '1.1',
    NULL,
    30,
    5
  ),
  (
    4,
    1,
    'Describe these pictures.',
    '1.2',
    'https://i.ibb.co/HfdSYrNJ/test1.png',
    45,
    10
  ),
  (
    5,
    1,
    'What are the advantages of running over playing chess?',
    '1.2',
    NULL,
    30,
    5
  ),
  (
    6,
    1,
    'Which activity is more popular in your country? Running or chess?',
    '1.2',
    NULL,
    30,
    5
  ),
  (
    7,
    1,
    'Tell me about the item you dreamed of owning. Did you get it? Is luxury items old people want to have different from the ones young people want to have?',
    '2',
    NULL,
    120,
    60
  ),
  (
    8,
    1,
    'Governments should ban single-use plastics.',
    '3',
    'https://i.ibb.co/FLFDVrXd/test1-3.png',
    120,
    60
  ) ON CONFLICT (id) DO NOTHING;